### ISSUE TITLE
No modsecurity events found in the specified file

### ISSUE THREAD

**Issue by ashishkpal** [molu8bits/modsecurity-parser#15]
hi,

i am facing issue that when i am running  python3 modsecurity-parser.py -f /var/log/modsec_audit.log i am getting below error. please help to resolve the same and attached is the sample logs which i am getting 

inputFileName : /var/log/modsec_audit.log
No modsecurity events found in the specified file

[modsec_audit.log](https://github.com/molu8bits/modsecurity-parser/files/6161813/modsec_audit.log)

**Comment by molu8bits** [comment]
Hi,

Can you provide the version of the modsecurity and nginx ?

**Comment by bartoszx** [comment]
Hello
Same here.
Nginx 1.13.12
Modescurity latest (git clone -b v3/master)

**Comment by molu8bits** [comment]
@ashishkpal  and @bartoszx 
Probably you missed the flag "--version3".

When I ran parser for the attached modsec_audit.log I got:
```bash
python3 ./modsecurity-parser/modsecurity-parser.py -f modsec_audit.log --version3
inputFileName : modsec_audit.log
---------- modsec_audit events processed: 13    ----------
---------- modsec_audit events skipped by INCLUDED/EXCLUDED options or INVALID : 0 ----------
````
