### ISSUE TITLE
ValueError: Single argument to subplot must be a three-digit integer, not AxesSubplot(0.125,0.420962;0.149038x0.148077)

### ISSUE THREAD

**Issue by krazyipman** [molu8bits/modsecurity-parser#16]
Hi,

I tried to  use it on ModSecurity Version 3.

# python3 modsecurity-parser.py -f /var/log/modsec_audit.log --version3
inputFileName : /var/log/modsec_audit.log
---------- modsec_audit events processed: 249    ----------
---------- modsec_audit events skipped by INCLUDED/EXCLUDED options or INVALID : 0 ----------
modsecurity-parser.py:437: MatplotlibDeprecationWarning: Passing non-integers as three-element position specification is deprecated since 3.3 and will be removed two minor releases later.
  plt.subplot(ax21)
Traceback (most recent call last):
  File "modsecurity-parser.py", line 689, in <module>
    outputWithGraphs = modsecViewGraphs(modsec_entries)
  File "modsecurity-parser.py", line 437, in modsecViewGraphs
    plt.subplot(ax21)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 1272, in subplot
    key = SubplotSpec._from_subplot_args(fig, args)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/gridspec.py", line 632, in _from_subplot_args
    raise ValueError(
ValueError: Single argument to subplot must be a three-digit integer, not AxesSubplot(0.125,0.420962;0.149038x0.148077)

**Comment by anauwal** [comment]
-pip uninstall matplotlib
-pip install matplotlib==3.3.2

**Comment by geeksceo** [comment]
There are no solutions to solve the problem using the latest version of matplotlib?

**Comment by geeksceo** [comment]
There are no solutions to solve the problem using the latest version of matplotlib ?

**Comment by molu8bits** [comment]
Fixed requirements.txt
