### ISSUE TITLE
Doesn't work with ModSecurity 3.0

### ISSUE THREAD

**Issue by buzen247** [molu8bits/modsecurity-parser#2]
Haven't seen the log files for previous version but ModSecurity 3.0 Audit logs take the following pattern:
 ---PAbyO0H9---A--
This is different from the expected patter in the modsecurity-parser.py
```
# modsec_patterns
a_pattern = re.compile('^--\w{6,10}-A--$')
z_pattern = re.compile('^--\w{6,10}-Z--$')
```

**Comment by molu8bits** [comment]
I've just added some code to handle that new pattern (requires argument "--version3"). Not sure if it works, will check when my modsecurity3 reference lab is ready.

**Comment by molu8bits** [comment]
It works now with Modsecurity3 audit log. An argument --version3 should be added.
