### ISSUE TITLE
Png Graph not show rule id

### ISSUE THREAD

**Issue by matteocostantini** [molu8bits/modsecurity-parser#24]
![image](https://user-images.githubusercontent.com/5763421/230714319-51ca6758-522c-4c6f-b465-b4d5744d91c2.jpeg)

**Comment by khurshid-alam** [comment]
Yes, same issue here. Using Python 3.8.10 on windows 11.

**Comment by molu8bits** [comment]
Typo error in 618 line. Should start with:
`f'{i} --> {j} hits'`
instead of current:
`'f{i} --> {j} hits'`

I am going to fix it in soon.

**Comment by molu8bits** [comment]
@khurshid-alam  @matteocostantini 
Fixed with latest 0.5.0 version

**Comment by khurshid-alam** [comment]
Thanka. It is working now.
