### ISSUE TITLE
LogParts Setting

### ISSUE THREAD

**Issue by matteocostantini** [molu8bits/modsecurity-parser#26]
Hi , What is the perfect Parts string for your test?

**Comment by molu8bits** [comment]
Hi, 
What do you mean by "perfect Parts string" ?
Folder sample_audit_log currently consists of only one log sample - standard modsecurity2+Apache2 output log. I am going to add the rest of examples with the next update (e.g. modsecurity3, json etc). All of the samples are listed in current Makefile.

**Comment by molu8bits** [comment]
@matteocostantini 
Now you can find few examples of different modsecurity audit logs inside sample_audit_log. If you have a different log let me know.
