### ISSUE TITLE
in Detection only mode on hapee-2.4/libmodsecurity3  no rules are displayed in the report 

### ISSUE THREAD

**Issue by idlogin** [molu8bits/modsecurity-parser#28]
I've used modsecurity_parser.py to analyse a 27gb modsec_audit.log file with over 4.5million modsec events spread over a total of 171 million rows.

the issue is that it's giving no insight on the rules that are passed and so i get no intel when running modsec on haproxy enterprise in the  Dectection only mode.  Is there a way this can be enabled?. Thanks for a great tool!

![18-20_modsec_audit_2023-04-23_22-31-06](https://user-images.githubusercontent.com/49194174/233962325-6d346170-46e2-4a27-94fe-bb8b0e8326ff.png)

**Comment by Schroeffu** [comment]
exactly the same here, top Rule IDs are not shown. With also "detection only" (passed) configured. 

`modsec-crs 3.3.0` and `libapache2-mod-security2 2.9.3` (debian11)

**Comment by molu8bits** [comment]
@Schroeffu  @idlogin - please check the latest release. Fix for this bug has been included.

**Comment by Schroeffu** [comment]
> @Schroeffu @idlogin - please check the latest release. Fix for this bug has been included.

thanks for the fix! it takes a while for my test, i've used your docker image because the local run on my manjaro was not working out of the box. the docker image seems to be the old version.

i'll make it run locally and let you know.

**Comment by idlogin** [comment]
> @Schroeffu @idlogin - please check the latest release. Fix for this bug has been included.

i can confirm the report now shows the rule ID's in detectiononly mode. Thanks for the fix!

<img width="397" alt="image" src="https://user-images.githubusercontent.com/49194174/236160255-e775b049-6efe-41f4-8228-9788cb614cd7.png">

**Comment by Schroeffu** [comment]
same here, now could check it without docker. works again, rule IDs are shown. thank you very much!
